import { PrismaClient, Prisma } from "@prisma/client";

const prisma = new PrismaClient({ errorFormat: "pretty" });

const branchData = [
  { branchName: "CSE" },
  { branchName: "ECE" },
  { branchName: "IT" },
  { branchName: "EEE" },
  { branchName: "MECH" },
  { branchName: "MET" },
  { branchName: "CIVIL" },
  { branchName: "OTHER" },
];

const categoryData = [
  { categoryName: "OC" },
  { categoryName: "BC-A" },
  { categoryName: "BC-B" },
  { categoryName: "BC-C" },
  { categoryName: "BC-D" },
  { categoryName: "BC-E" },
  { categoryName: "SC" },
  { categoryName: "ST" },
  { categoryName: "EWS" },
  { categoryName: "PH" },
  { categoryName: "NCC" },
  { categoryName: "CAP" },
  { categoryName: "SPORTS" },
];

const communityData = [
  { communityName: "OC" },
  { communityName: "BC" },
  { communityName: "SC" },
  { communityName: "ST" },
  { communityName: "OTHERS" },
];

const examsData = [
  { examName: "EAPCET" },
  { examName: "PGCET" },
  { examName: "ECET" },
  { examName: "ICET" },
  { examName: "GATE" },
  { examName: "OTHER" },
];

const skillsData = [
{  skillName:".NET"},
{ skillName:"360-degree video"},
{ skillName:"3D Animation"},
{ skillName:"3D Design"},
{ skillName:"3D Model Maker"},
{ skillName:"3D Modelling"},
{ skillName:"3D Printing"},
{ skillName:"3D Rendering"},
{ skillName:"3ds Max"},
{ skillName:"4D"},
{ skillName:"Academic Writing"},
{ skillName:"Accounting"},
{ skillName:"ActionScript"},
{ skillName:"Active Directory"},
{ skillName:"Ad Planning / Buying"},
{ skillName:"Adobe Air"},
{ skillName:"Adobe Captivate"},
{ skillName:"Adobe Dreamweaver"},
{ skillName:"Adobe Fireworks"},
{ skillName:"Adobe Flash"},
{ skillName:"Adobe InDesign"},
{ skillName:"Adobe Lightroom"},
{ skillName:"Adobe LiveCycle Designer"},
{ skillName:"Adobe Premiere Pro"},
{ skillName:"Advertisement Design"},
{ skillName:"Advertising"},
{ skillName:"Aeronautical Engineering"},
{ skillName:"Aerospace Engineering"},
{ skillName:"Affiliate Marketing"},
{ skillName:"Afrikaans"},
{ skillName:"After Effects"},
{ skillName:"Agile Development"},
{ skillName:"Agronomy"},
{ skillName:"Air Conditioning"},
{ skillName:"Airbnb"},
{ skillName:"AJAX"},
{ skillName:"Albanian"},
{ skillName:"Algorithm"},
{ skillName:"Alibaba"},
{ skillName:"Amazon Fire"},
{ skillName:"Amazon Kindle"},
{ skillName:"Amazon Web Services"},
{ skillName:"AMQP"},
{ skillName:"Analytics"},
{ skillName:"Android"},
{ skillName:"Android Honeycomb"},
{ skillName:"Android Wear SDK"},
{ skillName:"Angular.js"},
{ skillName:"Animation"},
{ skillName:"Antenna Services"},
{ skillName:"Anything Goes"},
{ skillName:"Apache"},
{ skillName:"Apache Ant"},
{ skillName:"Apache Solr"},
{ skillName:"App Designer"},
{ skillName:"App Developer"},
{ skillName:"Appcelerator Titanium"},
{ skillName:"Apple Compressor"},
{ skillName:"Apple iBooks Author"},
{ skillName:"Apple Logic Pro"},
{ skillName:"Apple Motion"},
{ skillName:"Apple Safari"},
{ skillName:"Apple Watch"},
{ skillName:"Applescript"},
{ skillName:"Appliance Installation"},
{ skillName:"Appliance Repair"},
{ skillName:"Arabic"},
{ skillName:"Arduino"},
{ skillName:"Argus Monitoring Software"},
{ skillName:"Article Rewriting"},
{ skillName:"Article Submission"},
{ skillName:"Articles"},
{ skillName:"Artificial Intelligence"},
{ skillName:"Arts / Crafts"},
{ skillName:"AS400 / iSeries"},
{ skillName:"Asbestos Removal"},
{ skillName:"ASP"},
{ skillName:"ASP.NET"},
{ skillName:"Asphalt"},
{ skillName:"Assembly"},
{ skillName:"Asterisk PBX"},
{ skillName:"Astrophysics"},
{ skillName:"Attic Access Ladders"},
{ skillName:"Attorney"},
{ skillName:"Audio Production"},
{ skillName:"Audio Services"},
{ skillName:"Audit"},
{ skillName:"Augmented Reality"},
{ skillName:"AutoCAD"},
{ skillName:"Autodesk Inventor"},
{ skillName:"Autodesk Revit"},
{ skillName:"AutoHotkey"},
{ skillName:"Automotive"},
{ skillName:"Autotask"},
{ skillName:"Awnings"},
{ skillName:"Axure"},
{ skillName:"Azure"},
{ skillName:"backbone.js"},
{ skillName:"Balsamiq"},
{ skillName:"Balustrading"},
{ skillName:"Bamboo Flooring"},
{ skillName:"Banner Design"},
{ skillName:"Basque"},
{ skillName:"Bathroom"},
{ skillName:"Bengali"},
{ skillName:"Big Data"},
{ skillName:"BigCommerce"},
{ skillName:"Binary Analysis"},
{ skillName:"Biology"},
{ skillName:"Biotechnology"},
{ skillName:"Bitcoin"},
{ skillName:"Biztalk"},
{ skillName:"Blackberry"},
{ skillName:"Blog"},
{ skillName:"Blog Design"},
{ skillName:"Blog Install"},
{ skillName:"Bluetooth Low Energy (BLE)"},
{ skillName:"BMC Remedy"},
{ skillName:"Book Artist"},
{ skillName:"Book Writing"},
{ skillName:"Bookkeeping"},
{ skillName:"Boonex Dolphin"},
{ skillName:"Bootstrap"},
{ skillName:"Bosnian"},
{ skillName:"Bower"},
{ skillName:"BPO"},
{ skillName:"Brackets"},
{ skillName:"Brain Storming"},
{ skillName:"Branding"},
{ skillName:"Bricklaying"},
{ skillName:"Broadcast Engineering"},
{ skillName:"Brochure Design"},
{ skillName:"BSD"},
{ skillName:"Building"},
{ skillName:"Building Architecture"},
{ skillName:"Building Certifiers"},
{ skillName:"Building Consultants"},
{ skillName:"Building Designer"},
{ skillName:"Building Surveyors"},
{ skillName:"Bulgarian"},
{ skillName:"Bulk Marketing"},
{ skillName:"Business Analysis"},
{ skillName:"Business Cards"},
{ skillName:"Business Catalyst"},
{ skillName:"Business Coaching"},
{ skillName:"Business Intelligence"},
{ skillName:"Business Plans"},
{ skillName:"Business Writing"},
{ skillName:"Buyer Sourcing"},
{ skillName:"C Programming"},
{ skillName:"C# Programming"},
{ skillName:"C++ Programming"},
{ skillName:"CAD/CAM"},
{ skillName:"CakePHP"},
{ skillName:"Call Center"},
{ skillName:"Call Control XML"},
{ skillName:"Capture NX2"},
{ skillName:"Caricature / Cartoons"},
{ skillName:"Carpentry"},
{ skillName:"Carpet Repair / Laying"},
{ skillName:"Carports"},
{ skillName:"Cartography / Maps"},
{ skillName:"Carwashing"},
{ skillName:"CasperJS"},
{ skillName:"Cassandra"},
{ skillName:"Catalan"},
{ skillName:"Catch Phrases"},
{ skillName:"CATIA"},
{ skillName:"Ceilings"},
{ skillName:"Cement Bonding Agents"},
{ skillName:"CGI"},
{ skillName:"Chef Configuration Management"},
{ skillName:"Chemical Engineering"},
{ skillName:"Chordiant"},
{ skillName:"Christmas"},
{ skillName:"Chrome OS"},
{ skillName:"Cinema 4D"},
{ skillName:"Circuit Design"},
{ skillName:"Cisco"},
{ skillName:"Civil Engineering"},
{ skillName:"Classifieds Posting"},
{ skillName:"Clean Technology"},
{ skillName:"Cleaning Carpet"},
{ skillName:"Cleaning Domestic"},
{ skillName:"Cleaning Upholstery"},
{ skillName:"Climate Sciences"},
{ skillName:"CLIPS"},
{ skillName:"Clothesline"},
{ skillName:"Cloud Computing"},
{ skillName:"CMS"},
{ skillName:"Coating Materials"},
{ skillName:"COBOL"},
{ skillName:"Cocoa"},
{ skillName:"Codeigniter"},
{ skillName:"Coding"},
{ skillName:"Cold Fusion"},
{ skillName:"Columns"},
{ skillName:"Commercial Cleaning"},
{ skillName:"Commercials"},
{ skillName:"Communications"},
{ skillName:"Compliance"},
{ skillName:"Computer Graphics"},
{ skillName:"Computer Help"},
{ skillName:"Computer Security"},
{ skillName:"Concept Art"},
{ skillName:"Concept Design"},
{ skillName:"Concreting"},
{ skillName:"Construction Monitoring"},
{ skillName:"Content Writing"},
{ skillName:"Contracts"},
{ skillName:"Conversion Rate Optimisation"},
{ skillName:"Cooking / Recipes"},
{ skillName:"Cooking / Baking"},
{ skillName:"Copy Typing"},
{ skillName:"Copywriting"},
{ skillName:"Corporate Identity"},
{ skillName:"Courses"},
{ skillName:"Covers / Packaging"},
{ skillName:"CRE Loaded"},
{ skillName:"Creative Design"},
{ skillName:"Creative Writing"},
{ skillName:"CRM"},
{ skillName:"Croatian"},
{ skillName:"Cryptography"},
{ skillName:"Crystal Reports"},
{ skillName:"CS-Cart"},
{ skillName:"CSS"},
{ skillName:"CubeCart"},
{ skillName:"CUDA"},
{ skillName:"Customer Service"},
{ skillName:"Customer Support"},
{ skillName:"Czech"},
{ skillName:"Damp Proofing"},
{ skillName:"Danish"},
{ skillName:"Dari"},
{ skillName:"Dart"},
{ skillName:"Data Entry"},
{ skillName:"Data Mining"},
{ skillName:"Data Processing"},
{ skillName:"Data Science"},
{ skillName:"Data Warehousing"},
{ skillName:"Database Administration"},
{ skillName:"Database Development"},
{ skillName:"Database Programming"},
{ skillName:"DataLife Engine"},
{ skillName:"Dating"},
{ skillName:"DDS"},
{ skillName:"Debian"},
{ skillName:"Debugging"},
{ skillName:"Decking"},
{ skillName:"Decoration"},
{ skillName:"Delivery"},
{ skillName:"Delphi"},
{ skillName:"Demolition"},
{ skillName:"Design"},
{ skillName:"Desktop Support"},
{ skillName:"Digital Design"},
{ skillName:"Disposals"},
{ skillName:"Django"},
{ skillName:"DNS"},
{ skillName:"DOS"},
{ skillName:"DotNetNuke"},
{ skillName:"Drafting"},
{ skillName:"Drains"},
{ skillName:"Drones"},
{ skillName:"Drupal"},
{ skillName:"Dthreejs"},
{ skillName:"Dutch"},
{ skillName:"Dynamics"},
{ skillName:"eBay"},
{ skillName:"eBooks"},
{ skillName:"eCommerce"},
{ skillName:"Editing"},
{ skillName:"Education / Tutoring"},
{ skillName:"edX"},
{ skillName:"Elasticsearch"},
{ skillName:"eLearning"},
{ skillName:"eLearning Designer"},
{ skillName:"Electrical Engineering"},
{ skillName:"Electricians"},
{ skillName:"Electronic Forms"},
{ skillName:"Electronics"},
{ skillName:"Email Developer"},
{ skillName:"Email Handling"},
{ skillName:"Email Marketing"},
{ skillName:"Embedded Software"},
{ skillName:"Ember.js"},
{ skillName:"Employment Law"},
{ skillName:"Energy"},
{ skillName:"Engineering"},
{ skillName:"Engineering Drawing"},
{ skillName:"English (UK)"},
{ skillName:"English (US)"},
{ skillName:"English Grammar"},
{ skillName:"English Spelling"},
{ skillName:"Entrepreneurship"},
{ skillName:"ePub"},
{ skillName:"Equipment Hire"},
{ skillName:"Erlang"},
{ skillName:"ERP"},
{ skillName:"Estonian"},
{ skillName:"Etsy"},
{ skillName:"Event Planning"},
{ skillName:"Event Staffing"},
{ skillName:"Excavation"},
{ skillName:"Excel"},
{ skillName:"Express JS"},
{ skillName:"Expression Engine"},
{ skillName:"Extensions / Additions"},
{ skillName:"Face Recognition"},
{ skillName:"Facebook Marketing"},
{ skillName:"Fashion Design"},
{ skillName:"Fashion Modeling"},
{ skillName:"Fencing"},
{ skillName:"Feng Shui"},
{ skillName:"Fiction"},
{ skillName:"FileMaker"},
{ skillName:"Filipino"},
{ skillName:"Filmmaking"},
{ skillName:"Final Cut Pro"},
{ skillName:"Finale / Sibelius"},
{ skillName:"Finance"},
{ skillName:"Financial Analysis"},
{ skillName:"Financial Markets"},
{ skillName:"Financial Planning"},
{ skillName:"Financial Research"},
{ skillName:"Finite Element Analysis"},
{ skillName:"Finnish"},
{ skillName:"Firefox"},
{ skillName:"Flash 3D"},
{ skillName:"Flashmob"},
{ skillName:"Flex"},
{ skillName:"Floor Coatings"},
{ skillName:"Flooring"},
{ skillName:"Flow Charts"},
{ skillName:"Flyer Design"},
{ skillName:"Flyscreens"},
{ skillName:"Food Takeaway"},
{ skillName:"Format / Layout"},
{ skillName:"Fortran"},
{ skillName:"Forum Posting"},
{ skillName:"Forum Software"},
{ skillName:"FPGA"},
{ skillName:"Frames / Trusses"},
{ skillName:"Freelance"},
{ skillName:"FreelancerAPI"},
{ skillName:"FreeSwitch"},
{ skillName:"French"},
{ skillName:"French (Canadian)"},
{ skillName:"Fundraising"},
{ skillName:"Furniture Assembly"},
{ skillName:"Furniture Design"},
{ skillName:"Game Consoles"},
{ skillName:"Game Design"},
{ skillName:"Game Development"},
{ skillName:"GameSalad"},
{ skillName:"Gamification"},
{ skillName:"GarageBand"},
{ skillName:"Gardening"},
{ skillName:"Gas Fitting"},
{ skillName:"Genealogy"},
{ skillName:"General Labor"},
{ skillName:"General Office"},
{ skillName:"Genetic Engineering"},
{ skillName:"Geolocation"},
{ skillName:"Geology"},
{ skillName:"Geospatial"},
{ skillName:"Geotechnical Engineering"},
{ skillName:"German"},
{ skillName:"Ghostwriting"},
{ skillName:"GIMP"},
{ skillName:"Git"},
{ skillName:"Glass / Mirror / Glazing"},
{ skillName:"Golang"},
{ skillName:"Google Adsense"},
{ skillName:"Google Adwords"},
{ skillName:"Google Analytics"},
{ skillName:"Google App Engine"},
{ skillName:"Google Cardboard"},
{ skillName:"Google Chrome"},
{ skillName:"Google Cloud Storage"},
{ skillName:"Google Earth"},
{ skillName:"Google Maps API"},
{ skillName:"Google Plus"},
{ skillName:"Google SketchUp"},
{ skillName:"Google Web Toolkit"},
{ skillName:"Google Webmaster Tools"},
{ skillName:"Google Website Optimizer"},
{ skillName:"GoPro"},
{ skillName:"GPGPU"},
{ skillName:"GPS"},
{ skillName:"Grails"},
{ skillName:"Grant Writing"},
{ skillName:"Graphic Design"},
{ skillName:"Grease Monkey"},
{ skillName:"Greek"},
{ skillName:"Growth Hacking"},
{ skillName:"Grunt"},
{ skillName:"Guttering"},
{ skillName:"Hadoop"},
{ skillName:"Hair Styles"},
{ skillName:"Handyman"},
{ skillName:"Haskell"},
{ skillName:"HBase"},
{ skillName:"Health"},
{ skillName:"Heating Systems"},
{ skillName:"Hebrew"},
{ skillName:"Helpdesk"},
{ skillName:"Heroku"},
{ skillName:"Hindi"},
{ skillName:"Hire me"},
{ skillName:"History"},
{ skillName:"Hive"},
{ skillName:"Home Automation"},
{ skillName:"Home Design"},
{ skillName:"Home Organization"},
{ skillName:"HomeKit"},
{ skillName:"Hot Water"},
{ skillName:"House Cleaning"},
{ skillName:"Housework"},
{ skillName:"HP Openview"},
{ skillName:"HTML"},
{ skillName:"HTML5"},
{ skillName:"Human Resources"},
{ skillName:"Human Sciences"},
{ skillName:"Hungarian"},
{ skillName:"iBeacon"},
{ skillName:"IBM BPM"},
{ skillName:"IBM Tivoli"},
{ skillName:"IBM Websphere Transformation Tool"},
{ skillName:"Icon Design"},
{ skillName:"IIS"},
{ skillName:"IKEA Installation"},
{ skillName:"Illustration"},
{ skillName:"Illustrator"},
{ skillName:"Imaging"},
{ skillName:"iMovie"},
{ skillName:"Indonesian"},
{ skillName:"Industrial Design"},
{ skillName:"Industrial Engineering"},
{ skillName:"Infographics"},
{ skillName:"Inspections"},
{ skillName:"Instagram"},
{ skillName:"Installation"},
{ skillName:"Instrumentation"},
{ skillName:"Insurance"},
{ skillName:"Interior Design"},
{ skillName:"Interiors"},
{ skillName:"Internet Marketing"},
{ skillName:"Internet Research"},
{ skillName:"Internet Security"},
{ skillName:"Interpreter"},
{ skillName:"Interspire"},
{ skillName:"Intuit QuickBooks"},
{ skillName:"Inventory Management"},
{ skillName:"Investment Research"},
{ skillName:"Invitation Design"},
{ skillName:"Ionic Framework"},
{ skillName:"iPad"},
{ skillName:"iPhone"},
{ skillName:"ISO9001"},
{ skillName:"Italian"},
{ skillName:"ITIL"},
{ skillName:"J2EE"},
{ skillName:"J2ME"},
{ skillName:"Jabber"},
{ skillName:"Japanese"},
{ skillName:"Java"},
{ skillName:"JavaFX"},
{ skillName:"Javascript"},
{ skillName:"JD Edwards CNC"},
{ skillName:"JDF"},
{ skillName:"Jewellery"},
{ skillName:"Joomla"},
{ skillName:"Journalist"},
{ skillName:"jQuery / Prototype"},
{ skillName:"JSON"},
{ skillName:"JSP"},
{ skillName:"Kannada"},
{ skillName:"Kinect"},
{ skillName:"Kitchen"},
{ skillName:"Knockout.js"},
{ skillName:"Korean"},
{ skillName:"Label Design"},
{ skillName:"LabVIEW"},
{ skillName:"Landing Pages"},
{ skillName:"Landscape Design"},
{ skillName:"Landscaping"},
{ skillName:"Landscaping / Gardening"},
{ skillName:"Laravel"},
{ skillName:"LaTeX"},
{ skillName:"Latvian"},
{ skillName:"Laundry and Ironing"},
{ skillName:"Lawn Mowing"},
{ skillName:"Leads"},
{ skillName:"Leap Motion SDK"},
{ skillName:"Legal"},
{ skillName:"Legal Research"},
{ skillName:"Legal Writing"},
{ skillName:"LESS/Sass/SCSS"},
{ skillName:"Life Coaching"},
{ skillName:"Lighting"},
{ skillName:"Linear Programming"},
{ skillName:"Link Building"},
{ skillName:"Linkedin"},
{ skillName:"Linnworks Order Management"},
{ skillName:"LINQ"},
{ skillName:"Linux"},
{ skillName:"Lisp"},
{ skillName:"Lithuanian"},
{ skillName:"LiveCode"},
{ skillName:"Locksmith"},
{ skillName:"Logistics / Shipping"},
{ skillName:"Logo Design"},
{ skillName:"Lotus Notes"},
{ skillName:"Lua"},
{ skillName:"Mac OS"},
{ skillName:"Macedonian"},
{ skillName:"Machine Learning"},
{ skillName:"Magento"},
{ skillName:"Magic Leap"},
{ skillName:"Mailchimp"},
{ skillName:"Mailwizz"},
{ skillName:"Make Up"},
{ skillName:"Makerbot"},
{ skillName:"Malay"},
{ skillName:"Malayalam"},
{ skillName:"Maltese"},
{ skillName:"Management"},
{ skillName:"Manufacturing"},
{ skillName:"Manufacturing Design"},
{ skillName:"Map Reduce"},
{ skillName:"MariaDB"},
{ skillName:"Market Research"},
{ skillName:"Marketing"},
{ skillName:"Marketplace Service"},
{ skillName:"Materials Engineering"},
{ skillName:"Mathematics"},
{ skillName:"Matlab and Mathematica"},
{ skillName:"Maya"},
{ skillName:"Mechanical Engineering"},
{ skillName:"Mechatronics"},
{ skillName:"Medical"},
{ skillName:"Medical Writing"},
{ skillName:"Metatrader"},
{ skillName:"MeteorJS"},
{ skillName:"Metro"},
{ skillName:"Microbiology"},
{ skillName:"Microcontroller"},
{ skillName:"Microsoft"},
{ skillName:"Microsoft Access"},
{ skillName:"Microsoft Exchange"},
{ skillName:"Microsoft Expression"},
{ skillName:"Microsoft Hololens"},
{ skillName:"Microsoft Office"},
{ skillName:"Microsoft Outlook"},
{ skillName:"Microsoft SQL Server"},
{ skillName:"Microsoft Visio"},
{ skillName:"Microstation"},
{ skillName:"Millwork"},
{ skillName:"Mining Engineering"},
{ skillName:"Minitlab"},
{ skillName:"MLM"},
{ skillName:"MMORPG"},
{ skillName:"Mobile App Testing"},
{ skillName:"Mobile Phone"},
{ skillName:"MODx"},
{ skillName:"MonetDB"},
{ skillName:"Moodle"},
{ skillName:"Mortgage Brokering"},
{ skillName:"Motion Graphics"},
{ skillName:"Moving"},
{ skillName:"MQTT"},
{ skillName:"Mural Painting"},
{ skillName:"Music"},
{ skillName:"MVC"},
{ skillName:"MYOB"},
{ skillName:"MySpace"},
{ skillName:"MySQL"},
{ skillName:"Nanotechnology"},
{ skillName:"Natural Language"},
{ skillName:"Network Administration"},
{ skillName:"Newsletters"},
{ skillName:"Nginx"},
{ skillName:"Ning"},
{ skillName:"Nintex Forms"},
{ skillName:"Nintex Workflow"},
{ skillName:"node.js"},
{ skillName:"Nokia"},
{ skillName:"Norwegian"},
{ skillName:"NoSQL Couch / Mongo"},
{ skillName:"Nutrition"},
{ skillName:"OAuth"},
{ skillName:"Objective C"},
{ skillName:"OCR"},
{ skillName:"Oculus Mobile SDK"},
{ skillName:"Odoo"},
{ skillName:"Online Writing"},
{ skillName:"Open Cart"},
{ skillName:"Open Journal Systems"},
{ skillName:"OpenBravo"},
{ skillName:"OpenCL"},
{ skillName:"OpenGL"},
{ skillName:"OpenSceneGraph"},
{ skillName:"OpenSSL"},
{ skillName:"OpenStack"},
{ skillName:"OpenVMS"},
{ skillName:"Oracle"},
{ skillName:"Order Processing"},
{ skillName:"Organizational Change Management"},
{ skillName:"OSCommerce"},
{ skillName:"Package Design"},
{ skillName:"Packing / Shipping"},
{ skillName:"Painting"},
{ skillName:"Palm"},
{ skillName:"Papiamento"},
{ skillName:"Parallax Scrolling"},
{ skillName:"Parallel Processing"},
{ skillName:"Parallels Automation"},
{ skillName:"Parallels Desktop"},
{ skillName:"Patents"},
{ skillName:"Pattern Making"},
{ skillName:"Pattern Matching"},
{ skillName:"Pavement"},
{ skillName:"PayPal API"},
{ skillName:"Payroll"},
{ skillName:"Paytrace"},
{ skillName:"PCB Layout"},
{ skillName:"PDF"},
{ skillName:"PEGA PRPC"},
{ skillName:"PencilBlue CMS"},
{ skillName:"Pentaho"},
{ skillName:"PeopleSoft"},
{ skillName:"Periscope"},
{ skillName:"Perl"},
{ skillName:"Personal Development"},
{ skillName:"Pest Control"},
{ skillName:"Pet Sitting"},
{ skillName:"Petroleum Engineering"},
{ skillName:"Phone Support"},
{ skillName:"PhoneGap"},
{ skillName:"Photo Editing"},
{ skillName:"Photography"},
{ skillName:"Photoshop"},
{ skillName:"Photoshop Coding"},
{ skillName:"Photoshop Design"},
{ skillName:"PHP"},
{ skillName:"Physics"},
{ skillName:"PICK Multivalue DB"},
{ skillName:"Pickup"},
{ skillName:"Pinterest"},
{ skillName:"Piping"},
{ skillName:"PLC / SCADA"},
{ skillName:"Plesk"},
{ skillName:"Plugin"},
{ skillName:"Plumbing"},
{ skillName:"Poet"},
{ skillName:"Poetry"},
{ skillName:"Polish"},
{ skillName:"Portuguese"},
{ skillName:"Portuguese (Brazil)"},
{ skillName:"Post-Production"},
{ skillName:"Poster Design"},
{ skillName:"PostgreSQL"},
{ skillName:"Powerpoint"},
{ skillName:"Powershell"},
{ skillName:"Pre-production"},
{ skillName:"Presentations"},
{ skillName:"Press Releases"},
{ skillName:"Prestashop"},
{ skillName:"Prezi"},
{ skillName:"Print"},
{ skillName:"Procurement"},
{ skillName:"Product Descriptions"},
{ skillName:"Product Design"},
{ skillName:"Product Management"},
{ skillName:"Product Sourcing"},
{ skillName:"Programming"},
{ skillName:"Project Management"},
{ skillName:"Project Scheduling"},
{ skillName:"Prolog"},
{ skillName:"Proofreading"},
{ skillName:"Property Development"},
{ skillName:"Property Law"},
{ skillName:"Property Management"},
{ skillName:"Proposal/Bid Writing"},
{ skillName:"Protoshare"},
{ skillName:"PSD to HTML"},
{ skillName:"PSD2CMS"},
{ skillName:"Psychology"},
{ skillName:"Public Relations"},
{ skillName:"Publishing"},
{ skillName:"Punjabi"},
{ skillName:"Puppet"},
{ skillName:"Python"},
{ skillName:"QlikView"},
{ skillName:"Qualtrics Survey Platform"},
{ skillName:"Quantum"},
{ skillName:"QuarkXPress"},
{ skillName:"QuickBase"},
{ skillName:"R Programming Language"},
{ skillName:"RapidWeaver"},
{ skillName:"Raspberry Pi"},
{ skillName:"Ray-tracing"},
{ skillName:"React.js"},
{ skillName:"Real Estate"},
{ skillName:"REALbasic"},
{ skillName:"Recruitment"},
{ skillName:"Red Hat"},
{ skillName:"Redis"},
{ skillName:"Redshift"},
{ skillName:"Regular Expressions"},
{ skillName:"Remote Sensing"},
{ skillName:"Removalist"},
{ skillName:"Renewable Energy Design"},
{ skillName:"Report Writing"},
{ skillName:"Research"},
{ skillName:"RESTful"},
{ skillName:"Resumes"},
{ skillName:"Reviews"},
{ skillName:"Risk Management"},
{ skillName:"Robotics"},
{ skillName:"Rocket Engine"},
{ skillName:"Romanian"},
{ skillName:"Roofing"},
{ skillName:"RTOS"},
{ skillName:"Ruby"},
{ skillName:"Ruby on Rails"},
{ skillName:"Russian"},
{ skillName:"RWD"},
{ skillName:"Sales"},
{ skillName:"Salesforce App Development"},
{ skillName:"Salesforce.com"},
{ skillName:"Samsung"},
{ skillName:"Samsung Accessory SDK"},
{ skillName:"SAP"},
{ skillName:"SAS"},
{ skillName:"Scala"},
{ skillName:"Scheme"},
{ skillName:"Scientific Research"},
{ skillName:"Screenwriting"},
{ skillName:"Script Install"},
{ skillName:"Scrum"},
{ skillName:"Scrum Development"},
{ skillName:"Sculpturing"},
{ skillName:"Search Engine Marketing"},
{ skillName:"Sencha / YahooUI"},
{ skillName:"SEO"},
{ skillName:"Serbian"},
{ skillName:"Sewing"},
{ skillName:"Sharepoint"},
{ skillName:"Shell Script"},
{ skillName:"Shopify"},
{ skillName:"Shopify Templates"},
{ skillName:"Shopping"},
{ skillName:"Shopping Carts"},
{ skillName:"Short Stories"},
{ skillName:"Siebel"},
{ skillName:"Sign Design"},
{ skillName:"Silverlight"},
{ skillName:"Simplified Chinese (China)"},
{ skillName:"Slogans"},
{ skillName:"Slovakian"},
{ skillName:"Slovenian"},
{ skillName:"Smarty PHP"},
{ skillName:"Snapchat"},
{ skillName:"Social Engine"},
{ skillName:"Social Media Marketing"},
{ skillName:"Social Networking"},
{ skillName:"Socket IO"},
{ skillName:"Software Architecture"},
{ skillName:"Software Development"},
{ skillName:"Software Testing"},
{ skillName:"Solaris"},
{ skillName:"Solidworks"},
{ skillName:"Sound Design"},
{ skillName:"Spanish"},
{ skillName:"Spanish (Spain)"},
{ skillName:"Spark"},
{ skillName:"Speech Writing"},
{ skillName:"Sphinx"},
{ skillName:"Splunk"},
{ skillName:"Sports"},
{ skillName:"SPSS Statistics"},
{ skillName:"SQL"},
{ skillName:"SQLite"},
{ skillName:"Squarespace"},
{ skillName:"Squid Cache"},
{ skillName:"Startups"},
{ skillName:"Stationery Design"},
{ skillName:"Statistical Analysis"},
{ skillName:"Statistics"},
{ skillName:"Steam API"},
{ skillName:"Sticker Design"},
{ skillName:"Storage Area Networks"},
{ skillName:"Storyboard"},
{ skillName:"Stripe"},
{ skillName:"Structural Engineering"},
{ skillName:"Subversion"},
{ skillName:"SugarCRM"},
{ skillName:"Supplier Sourcing"},
{ skillName:"Surfboard Design"},
{ skillName:"Swedish"},
{ skillName:"Swift"},
{ skillName:"Symbian"},
{ skillName:"Symfony PHP"},
{ skillName:"System Admin"},
{ skillName:"T-Shirts"},
{ skillName:"Tableau"},
{ skillName:"Tally Definition Language"},
{ skillName:"Tamil"},
{ skillName:"TaoBao API"},
{ skillName:"Tattoo Design"},
{ skillName:"Tax"},
{ skillName:"Tax Law"},
{ skillName:"Technical Support"},
{ skillName:"Technical Writing"},
{ skillName:"Tekla Structures"},
{ skillName:"Telecommunications Engineering"},
{ skillName:"Telemarketing"},
{ skillName:"Telephone Handling"},
{ skillName:"Telugu"},
{ skillName:"Templates"},
{ skillName:"Test Automation"},
{ skillName:"Testing / QA"},
{ skillName:"TestStand"},
{ skillName:"Textile Engineering"},
{ skillName:"Thai"},
{ skillName:"Tibco Spotfire"},
{ skillName:"Tiling"},
{ skillName:"Time Management"},
{ skillName:"Titanium"},
{ skillName:"Tizen SDK for Wearables"},
{ skillName:"Traditional Chinese (Hong Kong)"},
{ skillName:"Traditional Chinese (Taiwan)"},
{ skillName:"Training"},
{ skillName:"Transcription"},
{ skillName:"Translation"},
{ skillName:"Travel Writing"},
{ skillName:"Troubleshooting"},
{ skillName:"Tumblr"},
{ skillName:"Turkish"},
{ skillName:"Twitter"},
{ skillName:"Typescript"},
{ skillName:"TYPO3"},
{ skillName:"Typography"},
{ skillName:"Ubuntu"},
{ skillName:"Ukrainian"},
{ skillName:"Umbraco"},
{ skillName:"UML Design"},
{ skillName:"Unit4 Business World"},
{ skillName:"Unity 3D"},
{ skillName:"UNIX"},
{ skillName:"Urdu"},
{ skillName:"Usability Testing"},
{ skillName:"User Experience Design"},
{ skillName:"User Interface / IA"},
{ skillName:"User Interface Design"},
{ skillName:"Valuation / Appraisal"},
{ skillName:"Varnish Cache"},
{ skillName:"VB.NET"},
{ skillName:"vBulletin"},
{ skillName:"Vectorization"},
{ skillName:"Veeam"},
{ skillName:"Vehicle Signage"},
{ skillName:"Verilog"},
{ skillName:"VHDL"},
{ skillName:"VertexFX"},
{ skillName:"Video Broadcasting"},
{ skillName:"Video Editing"},
{ skillName:"Video Production"},
{ skillName:"Video Services"},
{ skillName:"Video Upload"},
{ skillName:"Videography"},
{ skillName:"Vietnamese"},
{ skillName:"Viral Marketing"},
{ skillName:"Virtual Assistant"},
{ skillName:"Virtual Worlds"},
{ skillName:"Virtuemart"},
{ skillName:"Virtuozzo"},
{ skillName:"Visa / Immigration"},
{ skillName:"Visual Arts"},
{ skillName:"Visual Basic"},
{ skillName:"Visual Basic for Apps"},
{ skillName:"Visual Foxpro"},
{ skillName:"Visual Merchandising"},
{ skillName:"Visualization"},
{ skillName:"VMware"},
{ skillName:"Voice Artist"},
{ skillName:"Voice Talent"},
{ skillName:"VoiceXML"},
{ skillName:"VoIP"},
{ skillName:"Volusion"},
{ skillName:"VPS"},
{ skillName:"vTiger"},
{ skillName:"Vuforia"},
{ skillName:"WatchKit"},
{ skillName:"Web Hosting"},
{ skillName:"Web Scraping"},
{ skillName:"Web Search"},
{ skillName:"Web Security"},
{ skillName:"Web Services"},
{ skillName:"webMethods"},
{ skillName:"WebOS"},
{ skillName:"Website Design"},
{ skillName:"Website Management"},
{ skillName:"Website Testing"},
{ skillName:"Weddings"},
{ skillName:"Weebly"},
{ skillName:"Welsh"},
{ skillName:"WHMCS"},
{ skillName:"WIKI"},
{ skillName:"Wikipedia"},
{ skillName:"Windows 8"},
{ skillName:"Windows API"},
{ skillName:"Windows CE"},
{ skillName:"Windows Desktop"},
{ skillName:"Windows Mobile"},
{ skillName:"Windows Phone"},
{ skillName:"Windows Server"},
{ skillName:"Wireframes"},
{ skillName:"Wireless"},
{ skillName:"Wix"},
{ skillName:"Wolfram"},
{ skillName:"WooCommerce"},
{ skillName:"Word"},
{ skillName:"Word Processing"},
{ skillName:"WordPress"},
{ skillName:"Workshops"},
{ skillName:"WPF"},
{ skillName:"Wufoo"},
{ skillName:"x86/x64 Assembler"},
{ skillName:"Xamarin"},
{ skillName:"Xero"},
{ skillName:"XML"},
{ skillName:"XMPP"},
{ skillName:"Xojo"},
{ skillName:"Xoops"},
{ skillName:"XPages"},
{ skillName:"XQuery"},
{ skillName:"XSLT"},
{ skillName:"Yahoo! Store Design"},
{ skillName:"Yard Work / Removal"},
{ skillName:"Yarn"},
{ skillName:"Yiddish"},
{ skillName:"Yii"},
{ skillName:"YouTube"},
{ skillName:"Zbrush"},
{ skillName:"Zen Cart"},
{ skillName:"Zend"},
{ skillName:"Zendesk"},
{ skillName:"Zoho"},
];

async function main() {
  console.log(`Start seeding ...`);

  // const college = await prisma.college.create({
  //   data: {
  //     collegeId: "JNTUGVCEV",
  //     collegeName: "JNTUGV College Of Engineering Vizianagaram",
  //   },
  // });

  // for (const u of programData) {
  //   const department = await prisma.program.create({
  //     data: {
  //       ...u,
  //       collegeId: college.collegeId,
  //     },
  //   });
  //   console.log(`Created department with id: ${department.id}`);
  // }
  // for (const u of branchData) {
  //   const department = await prisma.department.create({
  //     data: {
  //       ...u,
  //       collegeId: college.collegeId,
  //     },
  //   });
  //   console.log(`Created department with id: ${department.id}`);
  // }



  for (const u of skillsData) {
    const skill = await prisma.skills.create({
      data: u,
    });
    console.log(`Created skill with id: ${skill.id}`);
  }


// for (const u of categoryData) {
//   const category = await prisma.category.create({
//     data: u,
//   });
//   console.log(`Created category with id: ${category.id}`);
// }
// for (const u of communityData) {
//   const community = await prisma.community.create({
//     data: u,
//   });
//   console.log(`Created community with id: ${community.id}`);
// }
// for (const u of examsData) {
//   const exam = await prisma.admissionExams.create({
//     data: u,
//   });
//   console.log(`Created exams with id: ${exam.id}`);
// }
  console.log(`Seeding finished.`);
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
